name = "veracruz_demo"

[applications]

[applications.rust]
manifest = "examples/veracruz_demo/oak_app_manifest.toml"
out = "examples/veracruz_demo/bin/veracruz_demo.oak"

[applications.rust.modules]
module = { Cargo = { cargo_manifest = "examples/veracruz_demo/module/rust/Cargo.toml" } }
translator = { Cargo = { cargo_manifest = "examples/translator/module/rust/Cargo.toml" } }

[clients]
rust = { Cargo = { cargo_manifest = "examples/veracruz_demo/client/rust/Cargo.toml" }, additional_args = [
  "--root-tls-certificate=./examples/certs/local/ca.pem",
] }
