[package]
name = "veracruz_demo_grpc"
version = "0.1.0"
authors = ["Derek Miller <derek.miller@arm.com>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
prost = "*"
tonic = { version = "*", features = ["tls"] }

[build-dependencies]
oak_utils = "*"
